 color_theme: forest
day_night: true
font: my_font_set
description: ''
sharing_image: icon.png
twitter: jnixy
logo: icon.png
highlight: true
math: false
google_analytics: G-SM3ZNKKSHS
google_tag_manager: ''
google_site_verification: google-site-verification=5SV3L5wpBvv0uzRgjU2bE9Dto8C5mqYinPzAlOgIvi0
privacy_pack: false
date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
email: jnix@unomaha.edu
phone: 402 554 6157
address: '6001 Dodge Street 218 CPACS, Omaha, NE 68132'
office_hours: ''
contact_links:
  - icon: twitter
    icon_pack: fab
    name: DM Me
    link: 'https://twitter.com/jnixy'
map: 0
map_api_key: ''
latitude: '37.4275'
longitude: '-122.1697'
zoom: 15
plugins_css: []
plugins_js: []
gravatar: false
menu_align_right: false
reading_time: true
comment_count: true
section_pager: false
docs_section_pager: true
sharing: true
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
search:
  engine: 1
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
